version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-demo
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  java-sample-app:
    build: .
    container_name: java-sample-app
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres
      API_ENDPOINT: ${API_ENDPOINT}
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres", "5432", "--", "java", "-jar", "app.jar"]